### ISSUE TITLE
Pallet Optimizations based on clippy & rust analyzer troubleshooting

### ISSUE THREAD

**Issue by amatsonkali** [hashed-io/hashed-substrate#115]
In order to minimize the burden on the `rust analyzer` extension and the same IDE (vs code in this case), a set of optimizations are proposed.
- [x] Perform clippy optimizations (Abel)
  - [x] RBAC (Abel)
  - [x] Gated marketplaces 
- [x] Optimize storage maps, avoiding key double hashing
  - [x] RBAC (Abel)
  - [x] Gated marketplaces 

### Gated marketplace Optimizations
- [x] Transition from tight to light coupling the following pallets:
  - [x] Timestamp
  - [x] Uniques
  - [x] Fruniques

#### Suggestions

- [x] Check the latest commit before adding Offer unit tests

**Comment by didiermis** [comment]
I did the loose coupling for the timestamp pallet. Uniques pallet wasn't required since fruniques & uniques pallets are tightly coupled.  
I did a tight coupling with fruniques pallet in gated.marketplace pallet.
