### ISSUE TITLE
Proxy-pallet: Add transactions

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#149]
Continuing with the EOSIO migration to Substrate, we need to design the flow for the transactions:
-----------------------------------------------------------------
- [x] Remove unnecessary features/fields/calls/flows from EOSIO
- [x]  Determine datatypes
- [x]  Add needed storage maps
- [x] Determine needed structures
- [x] Add a timestamp for every transaction
- [x] Support multiple files
- -------------------------------------
Add the following extrinsics: 
* [x] add a single transaction
* [x] add multiple transactions
* [x] edit a single transaction
* [x] edit multiple transactions
* [x] delete a single transaction
-----------------------------------------------------
Transaction
- [x] Create transaction
- [x] Update transaction
- [x] Delete transaction

**Comment by didiermis** [comment]
Backend done.
@tlacloc
