### ISSUE TITLE
Proxy-pallet: Add drawdowns flow

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#150]
Continuing with the EOSIO migration to Substrate, we need to design the flow for the drawdowns:

- [x] Remove unnecessary features/fields/calls/flows from EOSIO
- [x] Determine datatypes
- [x] Add needed storage maps
- [x] Determine needed structures
- [x] Add timestamp for every drawdown
- [x] Support multiple files #155 
- [x] Initilialize drawdowns when a project is created
-----------------------------------------------------
Add drawdown status: 
- [x] Daft
- [x] Submitted
- [x] Rejected
- [x] Approved
-------------------------------------------------
Create every Drawdown type:
- [x] EB5
- [x] Developer Equity
- [x] Construction Loan
------------------------------------------------------------
Add the following extrinsics:
- [x] Initialize drawdowns
- [x] Reject drawdown
- [x] Create drawdown
- [x] Submit drawdown
- [x] Approve drawdown
-------------------------------------------------------

**Comment by didiermis** [comment]
Backend done.
@tlacloc
