### ISSUE TITLE
Proxy-pallet: Design a new accounting & reports system 

### ISSUE THREAD

**Issue by didiermis** [hashed-io/hashed-substrate#153]
In order to generate the reports, we need to integrate an accounting system to track budgets/transactions/drawdowns.
- [x] Design an accounting system
- [x] Determine storage maps
--------------------------------------------------------------------------
Integrate it with:
- [x] Projects
- [x] Budgets
- [x] Expenditures
- [x] Transactions
- [x] Drawdowns

**Comment by didiermis** [comment]
@garcia-alejandro I'm gonna need your help with this.

**Comment by garcia-alejandro** [comment]
Sure, we can schedule a meeting for that

**Comment by didiermis** [comment]
@tlacloc @garcia-alejandro  confirm if you guys can attend the meeting (check your Hashed calendar).

**Comment by didiermis** [comment]
Backend done  @tlacloc
