### ISSUE TITLE
Develop flow that manages the balances of a budget expenditure

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#164]

**Comment by didiermis** [comment]
Talking with the team, we deleted all the old flow related to the budgets (a feature from EOSIO) and moved that logic directly to the ExpenditureData<T> structure. We are pretty sure with the current design we can achieve the report's needs. 
@tlacloc please close this issue.

**Comment by didiermis** [comment]
Backend done.
@tlacloc
