### ISSUE TITLE
Budget expenditure creation flow

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#175]
**Description**
To define the creation of the budget expenditure, the front should have a template of defaults to let the user define which budget expenditure and pass to the back-end an array of budget expenditures expected to be created.

Back-end should manage the creation and validation of budget expenditures types.

**Suggested Solution**
This is the model of the data that the back-end should receive.
```js
[
  [ name, naics_code, jobs_multipier, budget, type ]
]
```
an example
```js
[
  [ "construction", 100, 1000, 100.00, hard_cost ],
  [ "furniture", 2341, 10, 120.00, soft_cost ],
]
```

**Comment by didiermis** [comment]
Duplicated. Closed.
