### ISSUE TITLE
Proxy-pallet: Flow to register multiple users at time

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#176]
The backend should support multiple registrations. 
When creating an user the backend should receive a vector of users with a given role as follows : [ {AccountId: 5Cc...1JDUZ, name: Alice Smith, role: Builder}, {AccountId: 5Cc...1JDUZ, name: Bob Peterson, role: Issuer}, .... ]

**Comment by didiermis** [comment]
@DaniPoot  actually extrinsic uses a: 
BoundedVec<(T::AccountId, FieldName, ProxyRole), T::MaxResgitrationsAtTime>

**Comment by didiermis** [comment]
Backend done.
