### ISSUE TITLE
Proxy-pallet: Design flow for users deletion

### ISSUE THREAD

**Issue by didiermis** [hashed-io/hashed-substrate#181]
Should we allow users' deletion from Proxy website?
One deletion per extrinsic call?
Multiple deletions per extrinsic call?
Use a different extrinsic or combine this flow with users_registration extrinsic?
An admin can be deleted from Proxy UI?
An administrator can delete another administrator?

**Comment by didiermis** [comment]
@DaniPoot @AugustoLara

**Comment by AugustoLara** [comment]
Should we allow users' deletion from Proxy website? Yes, removing them from the platform. 
One deletion per extrinsic call? Yes, one is enough to be safe.
Multiple deletions per extrinsic call?
Use a different extrinsic or combine this flow with users_registration extrinsic? whatever makes sense technically
An admin can be deleted from Proxy UI? yes, only by another Proxy Admin.
An administrator can delete another administrator? yes, only by another Proxy Admin.

If any of the above complicates the technical implementation, let go with whatever makes sense technically

**Comment by didiermis** [comment]
I updated validations & workflow.
Backend done.
@tlacloc
