### ISSUE TITLE
Proxy-pallet: Explore/Find a solution for Polkadot JS 

### ISSUE THREAD

**Issue by didiermis** [hashed-io/hashed-substrate#186]
We're using an array of bytes to store string types as:
```Rust
pub type CID = BoundedVec<u8, ConstU32<100>>
```

There are some extrinsic that edits certain data structures, i.e:
```Rust
		pub fn projects_edit_project(
			origin: OriginFor<T>, 
			project_id: [u8;32], 
			title: Option<BoundedVec<FieldName, T::MaxBoundedVecs>>,	
			description: Option<BoundedVec<FieldDescription, T::MaxBoundedVecs>>,
			image: Option<BoundedVec<CID, T::MaxBoundedVecs>>,
			address: Option<BoundedVec<FieldName, T::MaxBoundedVecs>>,
			completition_date: Option<u64>,  
		) -> DispatchResult {
			let who = ensure_signed(origin)?; // origin need to be an admin
			Self::do_edit_project(who, project_id, tittle, description, image, adress, completition_date)
		}
```

If we try to wrap the CID using a normal Option like: 
```Rust
Option<CID>  --> Option<BoundedVec<u8, ConstU32<100>>> --> Option<Bytes>
```
We got the following error: 
![image](https://user-images.githubusercontent.com/62629075/194571899-747de263-dfdd-4cc0-b98d-e0af966d7f25.png)

Currently, I'm using a BoundedVec inside another BoundedVec inside an Option as a hotfix...
```Rust
Option<BoundedVec<CID, T::MaxBoundedVecs>> 
--> Option<BoundedVec<BoundedVec<u8, ConstU32<100>>, T::MaxBoundedVecs>>,
```
We need to look for a better solution, IF POSSIBLE.

**Comment by amatsonkali** [comment]
Update from the performed tests:
- The encoding bug only affects polkadot-js front, the cli tool and the js library doesn't have it.
- Happens when enabling an optional bytes field (`Option<Vec<u8>>` or `Option<BoundedVec<u8,len>>`).
- It is present even when the optional bytes field is wrapped in a struct.
- An optional struct with mandatory bytes within doesn't have the bug.

To-do: 
- [x] Test `pallet-identity` approach: have an enum which emulates an option (e.g `None` and `Data(Bytes)`)

**Comment by amatsonkali** [comment]
Yes, it is possible to include an Optional bytes field by including a similar data struct:

```rust
#[derive(Clone, Eq, Encode, Decode, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen)]
pub enum Data {
  /// No data here.
  None,
  /// The data is stored directly.
  Raw(BoundedVec<u8, ConstU32<32>>),
}
```
and adding it as an extrinsic parameter:
```rust
pub fn do_something(origin: OriginFor<T>, something: u32, data : Data) -> DispatchResult{...}
```
