### ISSUE TITLE
View output descriptor for a vault

### ISSUE THREAD

**Issue by mgravitt** [hashed-io/hashed-substrate#19]
The screen should show: 
- list of NBV vaults
- button/action/form to create new NBV vaults
- button/action/form to create new proposal from a specific vault
- view output descriptor for a specific vault

**Comment by mgravitt** [comment]
@jmgayosso I think this is all completed except for View Output Descriptor for a vault... I am renaming it.

**Comment by jmgayosso** [comment]
> @jmgayosso I think this is all completed except for View Output Descriptor for a vault... I am renaming it.

Hi @3yekn what do you mean?  replace "Export descriptor" for "View output descriptor"?

**Comment by mgravitt** [comment]
There should be a mechanism to show the text-based output descriptor and not only the QR code.
