### ISSUE TITLE
Proxy-pallet: Develop a new query to get all drawdowns by status

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#199]
**Description**
For the notification part we need a query that retrieves all the drawdowns that matches a given status, project id and drawdown type.

**Suggested Solution**
The call would be something like this

key: DrawdonStatus
key2: project id
key3: DrawdownType

We need a query that retrieves an array of drawdowns ids
```rust
[]
```

**Alternatives**
Review if a storage maps is needed or maybe unsigned functions,

**Additional Information**
Maybe researching RPC calls or an indexer that could query this information.

**Comment by didiermis** [comment]
I implemented the required storagemap but after a deep review with the team, we concluded that is no longer needed. 
@tlacloc please close this issue.
