### ISSUE TITLE
Proxy-pallet: Bulkupload

### ISSUE THREAD

**Issue by didiermis** [hashed-io/hashed-substrate#217]
For bulkuploads, should we consider a draft status when administrators are capturing all transactions for a given drawdown?
Or when the administrators input the transactions, they are sent directly to approved status?
Should we consider a feedback at drawdown level for bulkuploads?

**Comment by didiermis** [comment]
Backend done. I updated the bulk-upload flow.  #218 
@tlacloc

**Comment by AugustoLara** [comment]
@didiermis are there any pending questions for me?
