### ISSUE TITLE
Proxy-pallet: Test transactions & drawdowns flow

### ISSUE THREAD

**Issue by didiermis** [hashed-io/hashed-substrate#223]
Test following flows/extrinsics: 
- [x] Send an EB5 drawdown as draft
- [x] Send an EB5 drawdown as submitted
- [x] Approve an EB5 drawdown 
- [x] Approve a Construction loan & developer equity drawdown 
- [x] Reject a drawdown
- [x] Up bulkupload

Extras:
- [x] Update validations if needed
- [x] Update flows
- [x] Fix bugs

**Comment by didiermis** [comment]
Backend done.
@tlacloc

**Comment by tlacloc** [comment]
Closing the ticket as the feature has been merge in #234
