### ISSUE TITLE
Error recovery workflows

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#295]
**Description**

Proxy Admin needs the ability to edit drawdowns or itemized bulk uploads that have been approved with mistakes.

**Suggested Solution**

- [x] Proxy Admin should be able to go into the historical drawdowns and edit one of the values.

- [x] An (edited) warning should be visible in the edited budget expenditure

**Related tickets**
- #389 
- #390
- #391
- #392

**Comment by didiermis** [comment]
@tlacloc Backend is done.
