### ISSUE TITLE
Evaluate subquery managed services for indexing solution deployment

### ISSUE THREAD

**Issue by sebastianmontero** [hashed-io/hashed-substrate#331]
Subquery provides hosting infrastructure for deployment of subquery projects:

- [x] Determine costs
- [x] Requirements for project deployment
- [x] Determine what monitoring options they provide
- [x] Determine the service level agreement 
- [x] Test it
- [x] Evaluate vs hosting and maintaining our infrastructure

**Comment by didiermis** [comment]
Subquery pricing:
https://project.subquery.network/pricing
![image](https://user-images.githubusercontent.com/62629075/217915326-19ada952-d1c7-4d2a-908f-25c48512e373.png)

**Comment by didiermis** [comment]
In their White Paper, I found the following table referring to the available payment methods:
![image](https://user-images.githubusercontent.com/62629075/217954322-81d263d7-29c2-4075-86f9-f8e5be179ca0.png)
Pages: [8, 10]
Link: https://static.subquery.network/whitepaper.pdf
There's also a related page on the official docs: https://academy.subquery.network/th/subquery_network/payment-methods.html#open-service-agreement
FAQ's: https://academy.subquery.network/faqs/faqs.html#how-much-does-it-cost-to-host-my-project-in-subquery-projects

**Comment by didiermis** [comment]
Requirements to run a SubQuery project:
- docker
- docker compose
- yarn/npm
- Node v12 or higher is required
- SubQuery CLI

I found the following helpful doc: https://academy.subquery.network/assets/pdf/Hello_World_Lab.pdf

**Comment by didiermis** [comment]
In the White Paper we can see the Risks and Disclaimers
Link: https://static.subquery.network/whitepaper.pdf
Pages [22, 25]

**Comment by didiermis** [comment]
About the Service Level Agreement, I found the following information:
- [Service Agreements](https://academy.subquery.network/glossary/glossary.html#service-agreements)
- [Closed Plans and Agreements](https://academy.subquery.network/subquery_network/payment-methods.html#closed-plans-and-agreements)
- [Open Service Agreement](https://academy.subquery.network/subquery_network/payment-methods.html#open-service-agreement)

TBH, those links don't provide helpful information.

**Comment by didiermis** [comment]
After I read the docs, I'm not sure whether a custom blockchain like ours, without being part of the Polkadot ecosystem, will be a candidate for SubQuery.
As far as I understand, SubQuery Supports any Polkadot relay chain.
https://academy.subquery.network/subquery_network/design-philosophy.html#multi-chain-by-design

**Comment by didiermis** [comment]
About hosting our own project:
- https://academy.subquery.network/run_publish/run.html
- https://academy.subquery.network/academy/tutorials_examples/run-indexer.html#postgres

**Comment by didiermis** [comment]
Using SubQuery maganed services:
- https://academy.subquery.network/run_publish/publish.html
