### ISSUE TITLE
Proof of reserve: new Finalizer tx and adjustements

### ISSUE THREAD

**Issue by amatsonkali** [hashed-io/hashed-substrate#383]
**Description**

The `is_finalized` within the `save_proof_psbt` extrinsic was considered unnecesary.
To finalize a proof, there must be a different extrinsic.

**Suggested Solution**

- [x] Refactor `save_proof_psbt` and remove the boolean finalizing flag. 
- [x] Put the Proof status on ReadyToFinalize(true)
- [x] Create new extrinsic to finalize the proof
- [x] Adapt an create the pertinent unit tests

**Comment by tlacloc** [comment]
closed as fixed on #384
