### ISSUE TITLE
Evaluate capabilities of RMRK 2.0 NFT spec

### ISSUE THREAD

**Issue by mgravitt** [hashed-io/hashed-substrate#4]
It seems RMRK does offer some nft parent-child capabilities.
- [x] Read the RMRK 2.0 standard
- [x] Explore the code (maybe make some diagrams?)
- [x] Clone the repo and get their node working locally
- [x] Play around with the nft's/extrinsics/queries and code some polkadotjs api scripts for interacting with the pallet
   - [x] Nfts & collection queries (5/5)
   - [x] Nfts & collection tx (6/6)
-  Add the rmrk-core pallet to a hashed-substrate testing branch to ensure compatibility
   - [x] Decouple the uniques pallet from the uniques
   -  Add external dependency and call the extrinsics through the front-end and/or the coded scripts
   -  Loosely couple and try to replicate the current functionality of the fruniques spawn function
-  Generate documentation and determine if we should reuse partially (or completely) code/logic for the upcoming tasks (#7 & #8).

**Comment by amatsonkali** [comment]
Useful resources:
- [RMRK 2.0 standard](https://github.com/rmrk-team/rmrk-spec/tree/master/standards/rmrk2.0.0)

Having trouble by adding rmrk-core as an external dependency, so I've posted a [github issue](https://github.com/rmrk-team/rmrk-substrate/issues/74) asking for help

**Comment by amatsonkali** [comment]
Having troubles by adding rmrk-core as an external dependency, so I posted a [github issue](https://github.com/rmrk-team/rmrk-substrate/issues/74) on the rmrk repo asking for help.

**Comment by amatsonkali** [comment]
The rmrk pallets are not yet available as an external dependency :(
