### ISSUE TITLE
Implement mechanism to enable resiliency on the OCW

### ISSUE THREAD

**Issue by amatsonkali** [hashed-io/hashed-substrate#43]
**Prerrequisites**
- Research about storage migrations

**Alternatives**
- Store OCW errors by vault/proposal
- Add some sort of _off-chain status_  on Vaults and Proposal structs

**Comment by mgravitt** [comment]
Can you provide a bit more detail on this issue? How does it fail? Is there an error message and/or known root cause?

**Comment by amatsonkali** [comment]
Yes, there are a few ways the offchain worker could fail.
#### When inserting the a vault descriptor
- The xpubs are structurally invalid (or belong to another network)

#### When inserting a tx proposal
- The descriptor belongs to another network
- The vault does not have sufficient funds to cover the transaction fees

#### More details
- Failing entails a offchain `panic`, where the offchain worker would stop running even if there's pending vaults/proposals to be submited
- Offchain worker instances are independent from each other, so if one fails, another will try to repeat the process on the next imported block
- An offchain panic often looks like this on the node logs (`RUST_LOG=runtime=debug` needed on command that runs the node):
```bash
2022-06-01 16:09:06.011 ERROR      offchain-worker offchain-worker::http: Requested started id=162 method=POST uri=https://bdk.hashed.systems/gen_psbt

====================

Version: 0.1.0-dev-9deab15

   0: sp_panic_handler::set::{{closure}}

# Omiting the whole error stack...

Thread 'offchain-worker' panicked at 'Error while generating proposal: Error::Unknown', /home/abel/hashed/Back-end-projects/hashed-substrate/pallets/nbv-storage/src/functions.rs:116

This is a bug. Please report it at:

        https://hashed.systems

2022-06-01 16:09:06.558  WARN      offchain-worker pallet_nbv_storage::functions: Unexpected status code: 400    
2022-06-01 16:09:06.561 ERROR      offchain-worker offchain-worker: Error running offchain workers at BlockId::Hash(0x52768f087af632041e1219d1d1dad145411f3e7784ebdfff7e6c87889c9325ef): Execution failed: Runtime panicked: Error while generating proposal: Error::Unknown
2022-06-01 16:09:06.718  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #52 (0x5276…25ef), finalized #49 (0x8274…9e82), ⬇ 0 ⬆ 0  
```

### Proposed solution
As it is quite troublesome to add a regex dependency (none that I could find was `WASM` and `no_std` compatible), I'm opting to improve greatly the error handling on the Off-chain worker side by adding an `Offchain_status` on the `Vault` and `Proposal` data structures. The `Offchain_status` may change according to the following statuses:

```rust
Pending, // Default and initial value
Done, // Descriptors/PSBT inserted succesfully
RecoverableError(String), // Temporary failure (e.g BDK-services are down), the offchain worker may try again
IrrecoverableError(String), // The offchain worker should avoid generating/completing these requests. Assured failure
```
- The offchain worker would take the `Pending` and `RecoverableError` Vaults/Proposals to try to request the respective resource.
-  If `bdk-services` responds with a success,  the data would be inserted through an unsigned request and the Vault/Proposal `Offchain_status` would be set to `Done`
- If `bdk-services` responds with a failure, the offchain worker would change the `Offchain_status` to a `RecoverableError` or `IrrecoverableError` depending on the retrieved http code.
