### ISSUE TITLE
Historical reporting tool and block explorer

### ISSUE THREAD

**Issue by mgravitt** [hashed-io/hashed-substrate#50]
We will need to implement support for transaction history caching, reporting, and block exploration. There are a few existing options to review. 

Parity's Substrate Archive: https://github.com/paritytech/substrate-archive
Subquery: https://github.com/subquery
Subscan: https://github.com/subscan-explorer
Polkascan: https://github.com/polkascan
SubSquid: https://github.com/subsquid

The scope of this issue is to take a look into the options and select 1-2 to start with, and implement it. Ideally, there is a block explorer UI that we can link to from our applications, which I am pretty sure Subscan and Polkascan have, but I'm not sure about the others.

**Comment by mgravitt** [comment]
It might also be helpful to deploy something like the [api-sidecar](https://paritytech.github.io/substrate-api-sidecar/dist/), but with queries specific for marketplaces, offers, fruniques, etc. 

It could be an endpoint like:  
```
https://md5.network/api/marketplaces/1/items
https://md5.network/api/collection/3/item/5
```
Not a hard requirement, but just something to look at.

**Comment by didiermis** [comment]
My final thoughts about the above options: 
- Subquery & Subsquid are dedicated API's
- Subscan doesn't have good support, documentation and maintenance. 
- Polkascan is the one. We could adapt it and solve some issues related to Docker/MySql.
