### ISSUE TITLE
Marketplace Protocol

### ISSUE THREAD

**Issue by mgravitt** [hashed-io/hashed-substrate#57]
## Marketplace Roles
Each marketplace has an owner and administrator.

### Owner
Owner is required and enforced from signer. The owner may change the administrator. Owner is also a required signer to erase a marketplace, and specify accounts to use for commission payments, protocol fees, etc.

### Administrator
The Marketplace Administrator can approve:

- new market participants being allowed to originate assets or place orders
- new asset graders/appraisers
- new redemption specialists

### Asset Grader/Appraiser
This role has the authority to add a grade, score, or boolean to an asset. An asset may have many grades, and graders can edit their own, but graders may not have multiple simultaneous grades of the same asset.

There may be many of these roles, and they can set the price for their services.

### Redemption Specialist
This role is responsible for transforming the on-chain asset into the IRL asset. For example, to be redeemed, a tax credit NFT needs to be assigned to an identity and submitted to (IRS or states?). Or an asset may need to be mailed from a warehouse.

There may be many of these roles, and they can set the price for their services.

### Market Participant
This roles has the authority to originate and purchase assets.

### Arbitrator
This role has the authority to release escrowed funds in the case of a dispute.

## Fractionalizable
Each asset is infinitesimally fractionalizable. An asset starts as a single whole asset; n=1. The asset has an amount value. An asset owner can spawn a new asset from the original, parent asset and specify the amount value of the child. The pallet enforces the hierarchical math of the amount value on each spawn.

Children can inherit attributes from their parents, override them (if permitted by attribute-creator), or add new ones.

An example asset is a harvest of corn for a season. The farmer creates it as an asset measuring bushels, and then sells down that harvest by selling a few bushels at a time.

## Privacy Preserving Storage
Users can save data on the environment that is encrypted, and selectively decide which other users on the Network can view it. They can attach data linked to assets, marketplace applications/member requests, orders, etc.

The data may be any files, plaintext, json, or markdown, etc.

**Comment by tlacloc** [comment]
Hello @3yekn 

We have some questions related to this ticket.

Could you explain from owner the part that says "accounts to use for commission payments, protocol fees, etc."?

Also authorities can be added without being participants on the market?

What is the Redemption specialist flow? Is it like a registrar?

And last one, how does the arbitrator data flow looks like or the general actions that role can take?

**Comment by amatsonkali** [comment]
A sell/buy mechanism needs to be specified before implementing the market participant functionalities.
