### ISSUE TITLE
Gated marketplaces:  market participant (requires fruniques) actions

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#67]
- [x] Awaiting on question on #57.
- [x] Requires basic fruniques functionality #7 #8 and tentatively #60

## Requirement gathering
- [x] Perform regression tests on Afloat qa site, only the useful ones
- [x] Generate and propose documentation about order matching system (automatic matching or user accepts offers?)
- [x] Comparative document on LLC DAOS vs Afloat matching mechanism. Determine which features we'll taker from both in order to fulfill the requirements.

Allow a participant to
- [x] #91
- [x] #99 
- [x] #100 
- [x] cancel order
- [x] purchase order

**Comment by amatsonkali** [comment]
Most likely an offchain worker will be needed in order to implement an automatic order matching algorithm. Special error handling must be made on the offchain side and concurrency support must be declared.

**Comment by amatsonkali** [comment]
The traditional order cycle has 6 (very) specific steps. Not sure if all marketplaces need this kind of transitions:
- order created
- order matched
- transfer form generated (?)
- seller signature completed (?)
- agency approval (?)
- order filled (?)

### Participant actions
Buyers can: 
- purchase credits from their favorite seller
- place a bid order

Sellers can:
- place unused tax credits up for sale

### Additional considerations
- To sell Tax Credits on the Afloat marketplace, your tax credits need to be confirmed by an authority. (would that be an appraiser?)
- The implementation of HUSD (stable token) might bring changes to the current workflow
