### ISSUE TITLE
Gated marketplaces: List nft for sale

### ISSUE THREAD

**Issue by amatsonkali** [hashed-io/hashed-substrate#91]
_Ability for Tax Credit (NFT) owners to assign a price and list it for sale._

Implement a `list_for_sale` extrinsic in the `gated-marketplaces` pallet, which permits linking an nft to a marketplace and setting a price in tokens. 
- [x] Lightly couple the `fruniques` pallet within the `gated_marketplaces` pallet to gain access to its extrinsics.
- [x] Determine the best alternative to list a nft for sale
  - [x] Insert `price` and `marketplace_id` attributes in the specified nft using `fruniques.set_attributes` extrinsic 
  - [x] Declare all the necessary storage maps in `gated_marketplace` to keep track of which nfts are for sale in which marketplaces and its price
  - [x] Optional: Test the new `set_price`/`buy_item` extrinsics implemented on `uniques`, within polkadot version 0.9.27,and determine if we should use them.

Additional info
- Obviously the nft needs to be minted prior to being on sale.
- Only the current owner should be capable of putting the asset on sale.
- To avoid ownership conflicts, the nft should only be listed for sale in just one marketplace. 
- [loose coupling](https://docs.substrate.io/reference/how-to-guides/pallet-design/use-loose-coupling/)

**Comment by mgravitt** [comment]
> To avoid ownership conflicts, the nft should only be listed for sale in just one marketplace.

I think we should support this. The owner is listing it for sale (i.e. advertising it for sale) in both places. The NFT protocol might be to allow the marketplace to move it to fulfill an order, but it doesn't actually lock the NFT until an order is made. But in any case, I think we need to allow it to be listed for sale in multiple marketplaces.

**Comment by mgravitt** [comment]
It's the `approve_transfer` extrinsic
